tin/apps/assignments/urls.py
from django.urls import path

from . import views

app_name = "assignments"

urlpatterns = [
    path("<int:assignment_id>", views.show_view, name="show"),
    path("add/course/<int:course_id>", views.create_view, name="add"),
    path("<int:assignment_id>/edit", views.edit_view, name="edit"),
    path("<int:assignment_id>/delete", views.delete_view, name="delete"),
    path("<int:assignment_id>/grader", views.manage_grader_view, name="manage_grader"),
    path("<int:assignment_id>/grader/download", views.download_grader_view, name="download_grader"),
    path("<int:assignment_id>/files", views.manage_files_view, name="manage_files"),
    path(
        "<int:assignment_id>/files/download/<int:file_id>",
        views.download_file_view,
        name="download_file",
    ),
    path(
        "<int:assignment_id>/files/delete/<int:file_id>",
        views.delete_file_view,
        name="delete_file",
    ),
    path(
        "<int:assignment_id>/files/action/<int:action_id>",
        views.file_action_view,
        name="file_action",
    ),
    path(
        "<int:assignment_id>/students/<int:student_id>",
        views.student_submissions_view,
        name="student_submission",
    ),
    path("<int:assignment_id>/submit", views.submit_view, name="submit"),
    path("<int:assignment_id>/rerun", views.rerun_view, name="rerun"),
    path("<int:assignment_id>/quiz", views.quiz_view, name="quiz"),
    path("<int:assignment_id>/report", views.quiz_report_view, name="report"),
    path("<int:assignment_id>/end", views.quiz_end_view, name="quiz_end"),
    path("<int:assignment_id>/clear/<int:user_id>", views.quiz_clear_view, name="clear"),
    path("<int:assignment_id>/scores_csv", views.scores_csv_view, name="scores_csv"),
    path(
        "<int:assignment_id>/download_submissions",
        views.download_submissions_view,
        name="download_submissions",
    ),
    path("<int:assignment_id>/moss", views.moss_view, name="moss"),
    path("<int:assignment_id>/download_log", views.download_log_view, name="download_log"),
    path("folder/<int:course_id>/<int:folder_id>", views.show_folder_view, name="show_folder"),
    path("add/folder/<int:course_id>", views.create_folder_view, name="add_folder"),
    path("edit/folder/<int:course_id>/<int:folder_id>", views.edit_folder_view, name="edit_folder"),
    path(
        "delete/folder/<int:course_id>/<int:folder_id>",
        views.delete_folder_view,
        name="delete_folder",
    ),
    path("upload", views.upload_image, name="upload_image"),
]

tin/apps/auth/urls.py
from django.conf import settings
from django.contrib.auth import views as django_auth_views
from django.urls import path

from . import views

app_name = "auth"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]
if settings.DEBUG:
    urlpatterns.append(
        path(
            "password-login/",
            django_auth_views.LoginView.as_view(template_name="password-login.html"),
            name="password_login",
        )
    )

tin/apps/courses/urls.py
from django.urls import path

from . import views

app_name = "courses"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("<int:course_id>", views.show_view, name="show"),
    path("add/", views.create_view, name="create"),
    path("<int:course_id>/edit", views.edit_view, name="edit"),
    path("<int:course_id>/import", views.import_select_course_view, name="import_select_course"),
    path(
        "<int:course_id>/import/<int:other_course_id>",
        views.import_from_selected_course,
        name="import_from_selected_course",
    ),
    path("<int:course_id>/students", views.students_view, name="students"),
    path("<int:course_id>/students/import", views.import_students_view, name="import_students"),
    path("<int:course_id>/students/manage", views.manage_students_view, name="manage_students"),
    path("<int:course_id>/add_period", views.add_period_view, name="add_period"),
    path("<int:course_id>/edit_period/<int:period_id>", views.edit_period_view, name="edit_period"),
    path(
        "<int:course_id>/import/status/<str:task_id>",
        views.import_status_view,
        name="import_status",
    ),
]

tin/apps/submissions/urls.py
from django.urls import path

from . import views

app_name = "submissions"

urlpatterns = [
    path("<int:submission_id>", views.show_view, name="show"),
    path("<int:submission_id>.json", views.show_json_view, name="show_json"),
    path("<int:submission_id>/download", views.download_view, name="download"),
    path("<int:submission_id>/kill", views.kill_view, name="kill"),
    path("<int:submission_id>/rerun", views.rerun_view, name="rerun"),
    path("<int:submission_id>/comment", views.comment_view, name="comment"),
    path(
        "<int:submission_id>/comment/edit/<int:comment_id>",
        views.edit_comment_view,
        name="edit_comment",
    ),
    path(
        "<int:submission_id>/comment/delete/<int:comment_id>",
        views.delete_comment_view,
        name="delete_comment",
    ),
    path("<int:submission_id>/publish", views.publish_view, name="publish"),
    path("<int:submission_id>/unpublish", views.unpublish_view, name="unpublish"),
    path("filter", views.filter_view, name="filter"),
    path("set-aborted-complete", views.set_aborted_complete_view, name="set_aborted_complete"),
    path(
        "set-past-timeout-complete",
        views.set_past_timeout_complete_view,
        name="set_past_timeout_complete",
    ),
]

tin/apps/users/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("theme/", views.change_theme, name="theme"),
]

tin/apps/venvs/urls.py
from django.urls import path

from . import views

app_name = "venvs"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("<int:venv_id>", views.show_view, name="show"),
    path("add", views.create_view, name="add"),
    path("<int:venv_id>/install_packages", views.install_packages_view, name="install_packages"),
]

tin/urls.py
from django.contrib import admin
from django.urls import include, path

from tin.apps.errors.views import handle_404_view, handle_500_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("courses/", include("tin.apps.courses.urls", namespace="courses")),
    path("assignments/", include("tin.apps.assignments.urls", namespace="assignments")),
    path("submissions/", include("tin.apps.submissions.urls", namespace="submissions")),
    path("venvs/", include("tin.apps.venvs.urls", namespace="venvs")),
    path("", include("tin.apps.auth.urls", namespace="auth")),
    path("", include("social_django.urls", namespace="social")),
]

handler404 = handle_404_view
handler500 = handle_500_view

tin/apps/courses/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.urls import reverse


class CourseQuerySet(models.query.QuerySet):
    """Provide filtering utilities for courses."""

    def filter_visible(self, user):
        """Filters if a course is visible to a user.

        Admins can see all courses, teachers can only
        see course they teach, and students can only see non-archived
        courses OR courses that have permission "r" or "w"
        """
        if user.is_superuser:
            return self.all()
        else:
            return self.filter(
                Q(teacher=user)
                | (Q(students=user) & (Q(archived=False) | Q(permission="r") | Q(permission="w")))
            ).distinct()

    def filter_editable(self, user):
        """Filter courses a user can edit."""
        if user.is_superuser:
            return self.all()
        else:
            return self.filter(teacher=user).distinct()


class Course(models.Model):
    """A TJHSST Course

    e.g. Foundations of Computer Science
    """

    SORT_BY = (("due_date", "Due Date"), ("name", "Name"))
    PERMISSIONS = (
        ("w", "view and submit assignments"),
        ("r", "view assignments"),
        ("-", "see nothing"),
    )

    name = models.CharField(max_length=50, blank=False)
    teacher = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=False,
        related_name="taught_courses",
    )
    students = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="courses", blank=True)

    created = models.DateTimeField(auto_now_add=True)

    sort_assignments_by = models.CharField(max_length=30, choices=SORT_BY, default="due_date")

    archived = models.BooleanField(default=False)
    permission = models.CharField(max_length=1, choices=PERMISSIONS, default="r")

    objects = CourseQuerySet.as_manager()

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("courses:show", args=[self.id])

    def get_teacher_str(self) -> str:
        """Get a string of the last names of all teachers in a course"""
        return ", ".join(t.last_name for t in self.teacher.all())

    def is_student_in_course(self, user) -> bool:
        """Check if a student is registered in the course"""
        return self.students.contains(user)

    def is_only_student_in_course(self, user) -> bool:
        """Check if a user is the only student in a course"""
        return self.is_student_in_course(user) and not (
            user.is_superuser or user in self.teacher.all()
        )


class Period(models.Model):
    """A Period, or a Block

    e.g. Period 7
    """

    name = models.CharField(max_length=50, blank=False)
    course = models.ForeignKey(
        Course, null=True, on_delete=models.CASCADE, related_name="period_set"
    )

    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="taught_periods",
    )

    students = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="periods", blank=True)

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("courses:students", args=[self.course.id]) + f"?period={self.id}"


class StudentImportUser(models.Model):
    """A student that is to be added to a course when they log in"""

    user = models.CharField(max_length=15, unique=True)

    class Meta:
        verbose_name = "Imported Student"

    def __str__(self):
        return self.user

    def __repr__(self):
        return self.user


class StudentImport(models.Model):
    students = models.ManyToManyField(StudentImportUser, related_name="users")
    course = models.OneToOneField(Course, unique=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Student Import"

    def __str__(self):
        return f"Import into {self.course.name}"

    def __repr__(self):
        return f"Import into {self.course.name}"

    def get_absolute_url(self):
        return reverse("courses:import_students", args=[self.course.id])

    def queue_users(self, usernames):
        """Add usernames to a queue of students to add to a course"""
        for username in usernames:
            import_user_object = StudentImportUser.objects.get_or_create(user=username)[0]
            self.students.add(import_user_object)
        self.save()

tin/apps/users/forms.py
from django import forms


class UserMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, user):  # pylint: disable=arguments-differ
        return f"{user.full_name} ({user.username})"

tin/apps/venvs/forms.py
from django import forms

from ..assignments.models import Language
from .models import Venv


class VenvForm(forms.ModelForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["language"].queryset = Language.objects.filter(
            language="P", is_deprecated=False
        )

    class Meta:
        model = Venv
        fields = ["name", "language"]
        labels = {"language": "Python version"}

tin/apps/users/views.py
from __future__ import annotations

from django import http
from django.contrib.auth.decorators import login_required

from tin.apps.users.forms import ThemeForm


@login_required
def change_theme(request):
    """Sets the color theme"""
    if request.method == "POST":
        form = ThemeForm(request.POST)
        if form.is_valid():
            request.user.dark_mode = form.cleaned_data["dark_mode"]
            request.user.save()
            return http.JsonResponse({"success": True})
        else:
            return http.JsonResponse(
                {"success": False, "errors": form.errors.as_json()}, status=400
            )
    raise http.Http404

tin/apps/venvs/views.py
from django import http
from django.shortcuts import get_object_or_404, redirect, render

from ..assignments.models import Language
from ..auth.decorators import teacher_or_superuser_required
from .forms import VenvForm
from .models import Venv
from .tasks import create_venv, install_packages


# Create your views here.
@teacher_or_superuser_required
def index_view(request):
    """Show all venvs visible to a user

    Args:
        request: The request
    """
    venvs = Venv.objects.filter_visible(request.user)

    return render(
        request,
        "venvs/index.html",
        {
            "venvs_app": True,
            "venvs": venvs,
        },
    )


@teacher_or_superuser_required
def show_view(request, venv_id):
    """Show information about a venv

    Args:
        request: The request
        venv_id: The primary key of an instance of the :class:`.Venv` model
    """
    venv: Venv = get_object_or_404(Venv.objects.filter_visible(request.user), id=venv_id)

    return render(
        request,
        "venvs/show.html",
        {
            "venvs_app": True,
            "nav_item": venv.name,
            "venv": venv,
        },
    )


@teacher_or_superuser_required
def create_view(request):
    """Create a venv

    Args:
        request: The request
    """
    if request.method == "POST":
        form = VenvForm(request.POST)
        if form.is_valid():
            venv = form.save(commit=False)
            venv.fully_created = False
            venv.save()
            create_venv.delay(venv.id)
            return redirect("venvs:show", venv.id)
    else:
        form = VenvForm(initial={"language": Language.objects.filter(language="P").first()})
    return render(
        request,
        "venvs/edit_create.html",
        {
            "venvs_app": True,
            "nav_item": "Create virtual environment",
            "form": form,
        },
    )


@teacher_or_superuser_required
def edit_view(request, venv_id):
    """Edit a venv

    Args:
        request: The request
        venv_id: The primary key of an instance of the :class:`.Venv` model
    """
    venv = get_object_or_404(Venv.objects.filter_editable(request.user), id=venv_id)

    if request.method == "POST":
        form = VenvForm(data=request.POST, instance=venv)
        if form.is_valid():
            venv = form.save()
            return redirect("venvs:show", venv.id)
    else:
        form = VenvForm(instance=venv)

    return render(
        request,
        "courses/edit_create.html",
        {
            "venvs_app": True,
            "nav_item": "Edit",
            "venv": venv,
            "form": form,
        },
    )


@teacher_or_superuser_required
def install_packages_view(request, venv_id):
    """Install packages in a venv

    Args:
        request: The request
        venv_id: The primary key of an instance of the :class:`.Venv` model
    """
    if request.method == "POST":
        venv = get_object_or_404(
            Venv.objects.filter_editable(request.user), id=venv_id, installing_packages=False
        )

        venv.installing_packages = True
        venv.save()

        packages = list(filter(bool, request.POST.getlist("packages[]")))

        install_packages.delay(venv.id, packages)

        return redirect("venvs:show", venv.id)

    raise http.Http404

tin/templates/courses/edit_create.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Turn-In: {% if course %}{{ course.name }}: {{ nav_item }}{% else %}Create course{% endif %}
{% endblock %}

{% block head %}
  <script type="text/javascript">
    $(document).ready(function () {
      $("#id_students").selectize();
      $("#id_teacher").selectize();

      function togglePermission() {
        if ($('#id_archived').is(':checked')) {
          $("#permission").show(300);
        } else {
          $("#permission").hide(300);
        }
      }

      const archivedCheckbox = $("#id_archived");
      archivedCheckbox.on("change", togglePermission);
      if (!archivedCheckbox.is(":checked")) {
        $("#permission").hide();
      }
    });
  </script>
{% endblock %}

{% block main %}

  <h2>{% if course %}{{ course.name }}: {{ nav_item }}{% else %}Create course{% endif %}</h2>

  <form action="" method="post">
    {% csrf_token %}
    <div class="tbl">
      {% for field in form %}
      <div class="tbl-row" {% if field.name == "permission" %} id="{{ field.name }}" {% endif %}>
          <span class="tbl-cell bold" style="padding-right:5px;min-width:200px;">{{ field.label_tag }}</span>
          <span class="tbl-cell form-input">{{ field }}{% if field.help_text %}<br>{{ field.help_text }}{% endif %}</span>
        </div>
      {% endfor %}
    </div>
    <input class="tin-btn" type="submit" value="{% if course %}Save{% else %}Create{% endif %}">
  </form>

{% endblock %}

tin/templates/courses/home.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
          integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
      let expanded = false;

      $(document).ready(function () {
          toggle();
      });

      function toggle() {
          $('.dropdown-content').toggle();
          const toggleIcon = $('#toggle-icon');
          if (expanded) {
              toggleIcon.removeClass('fa-chevron-right').addClass('fa-chevron-down');
          } else {
              toggleIcon.removeClass('fa-chevron-down').addClass('fa-chevron-right');
          }
          expanded = !expanded;
      }

  </script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block main %}

  <div class="header">
    <h2 class="left">Courses</h2>
  </div>

  <ul id="course-list">
    {% for course in courses %}
      <li>
        <div class="left">
          <a href="{% url 'courses:show' course.id %}">{{ course.name }}</a>
          {% if course in courses_with_unsubmitted_assignments %}
            <br>
            <span class="italic">Unsubmitted assignments</span>
          {% endif %}
        </div>
        <div class="right">
          {% with studentcount=course.students.count %}
            Teachers: {{ course.get_teacher_str }}<br>
            {{ studentcount }} student{{ studentcount | pluralize }}
          {% endwith %}
        </div>
      </li>
    {% empty %}
      <li>
        <div class="left">
          <p>No courses to show</p>
        </div>
      </li>
    {% endfor %}
    {% if archived_courses %}
      <li>
        <div class="dropdown">
          <a id="archive-courses-toggle" onclick="toggle()">
            <i id="toggle-icon" class="fa fa-chevron-right"></i> Archived Courses
          </a>
          <div class="dropdown-content">
            <ul id="archive-list">
              {% for course in archived_courses %}
                <li>
                  <div class="left">
                    <a href="{% url 'courses:show' course.id %}">{{ course.name }}</a>
                  </div>
                  <div class="right">
                    {% with studentcount=course.students.count %}
                      Teachers: {{ course.get_teacher_str }} • {{ studentcount }} student{{ studentcount | pluralize }}
                    {% endwith %}
                  </div>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </li>
    {% endif %}
    {% if request.user.is_teacher or request.user.is_superuser %}
      <li>
        <div>
          <a class="tin-btn" href="{% url 'courses:create' %}">New course</a>
          <a class="tin-btn" href="{% url 'submissions:filter' %}">Filter submissions</a>
          <a class="tin-btn" href="{% url 'venvs:index' %}">Manage virtual environments</a>
          <a href="https://tjcsl.github.io/tin/" target="_blank" class="tin-btn"><i class="fa fa-book"></i> Tin documentation</a>
        </div>
      </li>
    {% endif %}
  </ul>

  {% if request.user.is_student %}
    <h2>Due in the next week</h2>
    <ul id="course-list">
      {% for assignment in due_soon_assignments %}
        <li>
          <div class="left">
            <a href="{% url "assignments:show" assignment.id %}">{% if assignment.is_quiz %}
              [QUIZ] {% endif %}{{ assignment.name }} &mdash; {{ assignment.course.name }}</a>{% if assignment.hidden %}
            <i> (Hidden)</i>{% endif %}
          </div>
          <div class="right">
            <span class="italic">Due {{ assignment.due }}</span>
            <a href="{% url "assignments:submit" assignment.id %}" class="tin-btn">Submit</a>
          </div>
        </li>
      {% empty %}
        <li>
          <div class="left">
            Nothing's due in the next week.
          </div>
        </li>
      {% endfor %}
    </ul>
    <h2>To Do</h2>
    <ul id="course-list">
      {% for assignment in unsubmitted_assignments %}
        <li>
          <div class="left">
            <a href="{% url "assignments:show" assignment.id %}">{% if assignment.is_quiz %}
              [QUIZ] {% endif %}{{ assignment.name }} &mdash; {{ assignment.course.name }}</a>{% if assignment.hidden %}
            <i> (Hidden)</i>{% endif %}
          </div>
          <div class="right">
            <span class="italic">Due {{ assignment.due }}</span>
            <a href="{% url "assignments:submit" assignment.id %}" class="tin-btn">Submit</a>
          </div>
        </li>
      {% empty %}
        <li>
          <div class="left">
            You're all caught up!
          </div>
        </li>
      {% endfor %}
    </ul>
  {% endif %}

  {% if request.user.is_superuser %}
    <h2>Administration</h2>
    <p><a class="tin-btn" href="{% url 'admin:index' %}">Django Administrative Interface</a></p>

    <form method="post" action="{% url 'submissions:set_aborted_complete' %}">
      {% csrf_token %}
      <input type="submit" value="Mark all aborted submissions as complete">
    </form>

    <form method="post" action="{% url 'submissions:set_past_timeout_complete' %}">
      {% csrf_token %}
      <input type="submit" value="Mark all submissions that have passed the grader timeout as complete">
    </form>
  {% endif %}
{% endblock %}

tin/templates/courses/show.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Turn-In: {{ course.name }}
{% endblock %}

{% block main %}

  <div class="header">
    <h2 class="left">{{ course.name }}</h2>
    {% if is_teacher or request.user.is_superuser %}
      {% if request.user.is_superuser %}
        <a class="right tin-btn" href="{% url 'admin:courses_course_change' course.id %}">Admin</a>
      {% endif %}
      <a class="right tin-btn" href="{% url 'assignments:manage_file_actions' course.id %}">Manage File Actions</a>
      <a class="right tin-btn" href="{% url 'courses:edit' course.id %}">Edit</a>
      <a class="right tin-btn" href="{% url 'courses:students' course.id %}">Students</a>
    {% endif %}
  </div>

  <p>
    Teachers: {{ course.get_teacher_str }}<br>
    {% if period and is_student %}Your Period: {{ period | join:", " }}{% endif %}<br>
    {{ course.students.count }} student{{ course.students.count | pluralize }}
  </p>

  <ul id="assignment-list">
    {% for folder in folders %}
      <li>
        <div class="left" style="min-height: 30px;">
          <i class="fa fa-folder"></i> <a
          href="{% url 'assignments:show_folder' course.id folder.id %}">{{ folder.name }}</a>
        </div>
      </li>
    {% endfor %}
    {% for assignment in assignments %}
      <li>
        <div class="left">
          <a href="{% url 'assignments:show' assignment.id %}">{% if assignment.is_quiz %}
            [QUIZ] {% endif %}{{ assignment.name }}</a>{% if assignment.hidden %}<i> (Hidden)</i>{% endif %}
          {% if assignment in unsubmitted_assignments %}
            <br>
            <span class="italic">Not submitted</span>
          {% endif %}
        </div>
        <div class="right">
          Due: {{ assignment.due }}<br>
          Points possible: {{ assignment.points_possible }}
        </div>
      </li>
    {% endfor %}
  </ul>

  {% if is_teacher or request.user.is_superuser %}
    <div>
      <a class="tin-btn" href="{% url 'assignments:add_folder' course.id %}">New folder</a>
      <a class="tin-btn" href="{% url 'assignments:add' course.id %}">New assignment</a>
      <a class="tin-btn" href="{% url 'courses:import_select_course' course.id %}">Import assignments</a>
    </div>
  {% endif %}

{% endblock %}

tin/templates/courses/students-all.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Turn-In: {{ course.name }}: Students
{% endblock %}

{% block main %}

  <h2>{{ course.name }}: Students</h2>

  <p>
    Teachers: {{ course.get_teacher_str }}<br>
    {% if period %}Your Period: {{ period | join:", " }}{% endif %}<br>
    {{ course.students.count }} student{{ course.students.count | pluralize }}
  </p>

  <a class="right tin-btn" href="{% url 'courses:add_period' course.id %}">New period</a>
  <a class="right tin-btn" href="{% url 'courses:import_students' course.id %}">Import students</a>
  <a class="right tin-btn" href="{% url 'courses:manage_students' course.id %}">Manage students</a>
  <br><br>

  <hr><br>
  <a class="right tin-btn" style="color:#4fab4f !important" href="{% url 'courses:students' course.id %}">All</a>
  {% for period in period_set %}
    <a class="right tin-btn" href="{% url 'courses:students' course.id %}?period={{ period.id }}">{{ period }}</a>
  {% endfor %}
  <br><br>

  <h4>All Students in Course</h4>
  <table id="student-list" class="has-border">
    <tr>
      <th style="min-width:150px">Name</th>
      <th>Period</th>
    </tr>
    {% for student, period in students.items %}
      <tr>
        <td>{{ student.full_name }} ({{ student.username }})</td>
        <td>{{ period | join:", " }}</td>
      </tr>
    {% endfor %}
    {% if not students %}
      <td colspan="2" class="italic center">No students</td>
    {% endif %}
  </table>

{% endblock %}

tin/templates/courses/students.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Turn-In: {{ course.name }}: Students
{% endblock %}

{% block main %}

  <h2>{{ course.name }}: Students</h2>

  <p>
    Teachers: {{ course.get_teacher_str }}<br>
    {% if period %}Your Period: {{ period | join:", " }}{% endif %}<br>
    {{ course.students.count }} student{{ course.students.count | pluralize }}
  </p>

  <a class="right tin-btn" href="{% url 'courses:add_period' course.id %}">New period</a>
  <a class="right tin-btn" href="{% url 'courses:import_students' course.id %}">Import students</a>
  <a class="right tin-btn" href="{% url 'courses:manage_students' course.id %}">Manage students</a>
  <br><br>

  <hr><br>
  <a class="right tin-btn" href="{% url 'courses:students' course.id %}">All</a>
  {% for period in period_set %}
    <a class="right tin-btn" {% if active_period.id == period.id %}style="color:#4fab4f !important"{% endif %}
       href="{% url 'courses:students' course.id %}?period={{ period.id }}">{{ period }}</a>
  {% endfor %}
  <br><br>

  <h4>Period: {{ active_period }}</h4>
  <p>
    {% if request.user.is_superuser %}
      <a class="tin-btn" href="{% url 'admin:courses_period_change' active_period.id %}">Admin</a>
    {% endif %}
    <a class="tin-btn" href="{% url 'courses:edit_period' course.id active_period.id %}">Edit</a>
  </p>

  <table id="student-list" class="has-border">
    <tr>
      <th style="min-width:150px">Name</th>
      <th>Missing Assignments</th>
    </tr>
    {% for student, missing in students %}
      <tr>
        <td>{{ student.full_name }} ({{ student.username }})</td>
        <td>{{ missing | join:", " }}</td>
      </tr>
    {% endfor %}
    {% if not students %}
      <td colspan="2" class="italic center">No students</td>
    {% endif %}
  </table>

{% endblock %}