tin/apps/assignments/urls.py
from django.urls import path

from . import views

app_name = "assignments"

urlpatterns = [
    path("<int:assignment_id>", views.show_view, name="show"),
    path("add/course/<int:course_id>", views.create_view, name="add"),
    path("<int:assignment_id>/edit", views.edit_view, name="edit"),
    path("<int:assignment_id>/delete", views.delete_view, name="delete"),
    path("<int:assignment_id>/grader", views.manage_grader_view, name="manage_grader"),
    path("<int:assignment_id>/grader/download", views.download_grader_view, name="download_grader"),
    path("<int:assignment_id>/files", views.manage_files_view, name="manage_files"),
    path(
        "<int:assignment_id>/files/download/<int:file_id>",
        views.download_file_view,
        name="download_file",
    ),
    path(
        "<int:assignment_id>/files/delete/<int:file_id>",
        views.delete_file_view,
        name="delete_file",
    ),
    path(
        "<int:assignment_id>/files/action/<int:action_id>",
        views.file_action_view,
        name="file_action",
    ),
    path(
        "<int:assignment_id>/students/<int:student_id>",
        views.student_submissions_view,
        name="student_submission",
    ),
    path("<int:assignment_id>/submit", views.submit_view, name="submit"),
    path("<int:assignment_id>/rerun", views.rerun_view, name="rerun"),
    path("<int:assignment_id>/quiz", views.quiz_view, name="quiz"),
    path("<int:assignment_id>/report", views.quiz_report_view, name="report"),
    path("<int:assignment_id>/end", views.quiz_end_view, name="quiz_end"),
    path("<int:assignment_id>/clear/<int:user_id>", views.quiz_clear_view, name="clear"),
    path("<int:assignment_id>/scores_csv", views.scores_csv_view, name="scores_csv"),
    path(
        "<int:assignment_id>/download_submissions",
        views.download_submissions_view,
        name="download_submissions",
    ),
    path("<int:assignment_id>/moss", views.moss_view, name="moss"),
    path("<int:assignment_id>/download_log", views.download_log_view, name="download_log"),
    path("folder/<int:course_id>/<int:folder_id>", views.show_folder_view, name="show_folder"),
    path("add/folder/<int:course_id>", views.create_folder_view, name="add_folder"),
    path("edit/folder/<int:course_id>/<int:folder_id>", views.edit_folder_view, name="edit_folder"),
    path(
        "delete/folder/<int:course_id>/<int:folder_id>",
        views.delete_folder_view,
        name="delete_folder",
    ),
    path("upload", views.upload_image, name="upload_image"),
]

tin/apps/auth/urls.py
from django.conf import settings
from django.contrib.auth import views as django_auth_views
from django.urls import path

from . import views

app_name = "auth"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]
if settings.DEBUG:
    urlpatterns.append(
        path(
            "password-login/",
            django_auth_views.LoginView.as_view(template_name="password-login.html"),
            name="password_login",
        )
    )

tin/apps/users/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("theme/", views.change_theme, name="theme"),
]

tin/apps/venvs/urls.py
from django.urls import path

from . import views

app_name = "venvs"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("<int:venv_id>", views.show_view, name="show"),
    path("add", views.create_view, name="add"),
    path("<int:venv_id>/install_packages", views.install_packages_view, name="install_packages"),
]

tin/urls.py
from django.contrib import admin
from django.urls import include, path

from tin.apps.errors.views import handle_404_view, handle_500_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("courses/", include("tin.apps.courses.urls", namespace="courses")),
    path("assignments/", include("tin.apps.assignments.urls", namespace="assignments")),
    path("submissions/", include("tin.apps.submissions.urls", namespace="submissions")),
    path("venvs/", include("tin.apps.venvs.urls", namespace="venvs")),
    path("", include("tin.apps.auth.urls", namespace="auth")),
    path("", include("social_django.urls", namespace="social")),
]

handler404 = handle_404_view
handler500 = handle_500_view

tin/apps/users/forms.py
from django import forms


class UserMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, user):  # pylint: disable=arguments-differ
        return f"{user.full_name} ({user.username})"

tin/apps/venvs/forms.py
from django import forms

from ..assignments.models import Language
from .models import Venv


class VenvForm(forms.ModelForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["language"].queryset = Language.objects.filter(
            language="P", is_deprecated=False
        )

    class Meta:
        model = Venv
        fields = ["name", "language"]
        labels = {"language": "Python version"}

tin/apps/assignments/views.py
import csv
import datetime
import logging
import os
import subprocess
import uuid
import zipfile
from io import BytesIO
from pathlib import Path

import celery
from django import http
from django.conf import settings
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import now
from django.views.decorators.http import require_POST

from ... import sandboxing
from ..auth.decorators import login_required, teacher_or_superuser_required
from ..courses.models import Course, Period
from ..submissions.models import PublishedSubmission, Submission
from ..submissions.tasks import run_submission
from ..users.models import User
from .forms import (
    AssignmentForm,
    FileSubmissionForm,
    FileUploadForm,
    FolderForm,
    GraderScriptUploadForm,
    ImageForm,
    MossForm,
    SubmissionCapForm,
    TextSubmissionForm,
)
from .models import Assignment, CooldownPeriod, QuizLogMessage, SubmissionCap
from .tasks import run_moss

logger = logging.getLogger(__name__)


@login_required
def show_view(request, assignment_id):
    """Shows an overview of the :class:`.Assignment`

    Args:
        request : The request
        assignment_id : the :class:`.Assignment` id
    """
    assignment: Assignment = get_object_or_404(
        Assignment.objects.filter_visible(request.user), id=assignment_id
    )
    course = assignment.course
    quiz_accessible = assignment.is_quiz and assignment.quiz_open_for_student(request.user)

    if course.is_only_student_in_course(request.user):
        submissions = Submission.objects.filter(student=request.user, assignment=assignment)
        latest_submission = submissions.latest() if submissions else None
        publishes = PublishedSubmission.objects.filter(student=request.user, assignment=assignment)
        graded_submission = publishes.latest().submission if publishes else latest_submission

        submission_limit = assignment.find_submission_cap(request.user)
        submissions_left = submission_limit - len(submissions)
        submissions_left = max(submissions_left, 0)

        if submissions_left == float("inf"):
            submissions_left = None
        if submission_limit == float("inf"):
            submission_limit = None

        return render(
            request,
            "assignments/show.html",
            {
                "course": assignment.course,
                "folder": assignment.folder,
                "assignment": assignment,
                "submissions": submissions.order_by("-date_submitted"),
                "latest_submission": latest_submission,
                "graded_submission": graded_submission,
                "is_student": course.is_student_in_course(request.user),
                "is_teacher": request.user in course.teacher.all(),
                "quiz_accessible": quiz_accessible,
                "within_submission_limit": assignment.within_submission_limit(request.user),
                "submissions_used": len(submissions),
                "submissions_left": submissions_left,
                "submission_limit": submission_limit,
            },
        )
    else:
        students_and_submissions = []
        new_since_last_login = None
        new_in_last_24 = None
        teacher_last_login = request.user.last_login
        time_24_hours_ago = now() - datetime.timedelta(days=1)

        query = request.GET.get("query", "")

        filter = request.GET.get("filter", "")

        period = request.GET.get("period", "")
        period_set = course.period_set.order_by("teacher", "name")

        if query:
            active_period = "query"
            student_list = course.students.filter(full_name__icontains=query).order_by(
                "last_name", "first_name"
            )
        elif filter:
            active_period = "filter"
            if filter == "no_submissions":
                student_list = (
                    course.students.exclude(submissions__assignment=assignment)
                    .order_by("last_name", "first_name")
                    .distinct()
                )
            elif filter == "with_submissions":
                student_list = (
                    course.students.filter(submissions__assignment=assignment)
                    .order_by("last_name", "first_name")
                    .distinct()
                )
            else:
                student_list = course.students.all().order_by("last_name", "first_name")
        elif period == "all":
            active_period = "all"
            student_list = course.students.all().order_by("last_name", "first_name")
        elif period == "none":
            active_period = "none"
            student_list = []
        elif period == "teachers":
            active_period = "teachers"
            student_list = course.teacher.all().order_by("last_name", "first_name")
        elif course.period_set.exists():
            if period == "":
                if request.user in course.teacher.all():
                    try:
                        period = (
                            course.period_set.filter(teacher=request.user).order_by("name")[0].id
                        )
                    except IndexError:
                        period = "none"
                else:
                    period = "none"

            if period == "none":
                active_period = "none"
                student_list = []
            else:
                active_period = get_object_or_404(
                    Period.objects.filter(course=course), id=int(period)
                )
                student_list = active_period.students.all().order_by("last_name", "first_name")
        else:
            active_period = "none"
            student_list = []

        for student in student_list:
            period = student.periods.filter(course=assignment.course)
            submissions = Submission.objects.filter(student=student, assignment=assignment)
            publishes = PublishedSubmission.objects.filter(student=student, assignment=assignment)
            latest_submission = submissions.latest() if submissions else None
            graded_submission = publishes.latest().submission if publishes else latest_submission

            if not assignment.is_quiz:
                if latest_submission:
                    new_since_last_login = latest_submission.date_submitted > teacher_last_login
                    new_in_last_24 = latest_submission.date_submitted > time_24_hours_ago
                students_and_submissions.append(
                    (
                        student,
                        period,
                        latest_submission,
                        graded_submission,
                        new_since_last_login,
                        new_in_last_24,
                    )
                )
            else:
                students_and_submissions.append(
                    (
                        student,
                        period,
                        latest_submission,
                        graded_submission,
                        assignment.quiz_ended_for_student(student),
                        assignment.quiz_locked_for_student(student),
                    )
                )

        context = {
            "course": course,
            "folder": assignment.folder,
            "assignment": assignment,
            "students_and_submissions": students_and_submissions,
            "log_file_exists": (
                os.path.exists(os.path.join(settings.MEDIA_ROOT, assignment.grader_log_filename))
            ),
            "is_student": course.is_student_in_course(request.user),
            "is_teacher": request.user in course.teacher.all(),
            "query": query,
            "filter": filter,
            "period_set": period_set,
            "active_period": active_period,
            "quiz_accessible": quiz_accessible,
        }

        submissions = Submission.objects.filter(student=request.user, assignment=assignment)
        publishes = PublishedSubmission.objects.filter(student=request.user, assignment=assignment)
        latest_submission = submissions.latest() if submissions else None
        graded_submission = publishes.latest().submission if publishes else latest_submission

        submission_limit = assignment.find_submission_cap(request.user)
        num_submissions = len(submissions)
        submissions_left = submission_limit - num_submissions
        submissions_left = max(submissions_left, 0)

        # render properly after submission cap is lowered (such as when the due date is passed)
        if submissions_left == float("inf"):
            submissions_left = None
        if submission_limit == float("inf"):
            submission_limit = None

        context.update(
            {
                "submissions": submissions.order_by("-date_submitted"),
                "latest_submission": latest_submission,
                "graded_submission": graded_submission,
                "within_submission_limit": assignment.within_submission_limit(request.user),
                "submissions_used": num_submissions,
                "submissions_left": submissions_left,
                "submission_limit": submission_limit,
            }
        )

        return render(request, "assignments/show.html", context)


@teacher_or_superuser_required
def create_view(request, course_id):
    """Creates an assignment

    Args:
        request: The request
        course_id: The id of the :class:`.Course`
    """
    course = get_object_or_404(Course.objects.filter_editable(request.user), id=course_id)

    if request.method == "POST":
        assignment_form = AssignmentForm(course, request.POST)
        if assignment_form.is_valid():
            assignment_form.instance.course = course
            assignment = assignment_form.save()

tin/apps/users/views.py
from __future__ import annotations

from django import http
from django.contrib.auth.decorators import login_required

from tin.apps.users.forms import ThemeForm


@login_required
def change_theme(request):
    """Sets the color theme"""
    if request.method == "POST":
        form = ThemeForm(request.POST)
        if form.is_valid():
            request.user.dark_mode = form.cleaned_data["dark_mode"]
            request.user.save()
            return http.JsonResponse({"success": True})
        else:
            return http.JsonResponse(
                {"success": False, "errors": form.errors.as_json()}, status=400
            )
    raise http.Http404

tin/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>{% block title %}Turn-In{% endblock %}</title>

  {% include "meta.html" %}

  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
  <link rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Open+Sans:100italic,400italic,700italic,100,400,700"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
          integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/themes/base/jquery-ui.min.css"
        integrity="sha512-8PjjnSP8Bw/WNPxF6wkklW6qlQJdWJc/3w/ZQPvZ/1bjVDkrrSqLe9mfPYrMxtnzsXFPc434+u4FHLnLjXTSsg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/jquery-ui.min.js"
          integrity="sha512-Ww1y9OuQ2kehgVWSD/3nhgfrb424O3802QYP/A5gPXoM4+rRjiKrjHdGxQKrMGQykmsJ/86oGdHszfcVgUr4hA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/css/selectize.default.min.css"
        integrity="sha512-pTaEn+6gF1IeWv3W1+7X7eM60TFu/agjgoHmYhAfLEU8Phuf6JKiiE8YmsNC0aCgQv4192s4Vai8YZ6VNM6vyQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/js/selectize.min.js"
          integrity="sha512-IOebNkvA/HZjMM7MxL0NYeLYEalloZ8ckak+NDtOViP7oiYzG5vn6WVXyrJDiJPhl4yRdmNAG49iuLmhkUdVsQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css"
        integrity="sha512-hasIneQUHlh06VNBe7f6ZcHmeRTLIaQWFd43YriJ0UND19bvYRauxthDg8E4eVNPm9bRUhr5JGeqH7FRFXQu5g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"
          integrity="sha512-D9gUyxqja7hBtkWpPWGt9wfbfaMGVt9gnyCvYa+jojwwPHLCzUm5i8rpk7vD7wNee9bA35eYIjobYPaQuKS1MQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js"
          integrity="sha512-axd5V66bnXpNVQzm1c7u1M614TVRXXtouyWCE+eMYl8ALK8ePJEs96Xtx7VVrPBc0UraCn63U1+ARFI3ofW+aA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
      hljs.highlightAll();
      hljs.initLineNumbersOnLoad();
  </script>
  <script>
      $(function () {
          $(".continuous-progress").css({height: "15px"}).progressbar({value: false})
      });
  </script>
  {% block head %}{% endblock %}
</head>

<body>

<div id="nav">
  <ul class="no-list">
    <li><a href="{% url 'auth:index' %}"><h1><span class="logo"></span>Turn-In</h1></a></li>
    {% if request.user.is_authenticated %}
      {% if course %}
        <li><i class="fa fa-chevron-right"></i></li>
        <li><a href="{% url 'courses:show' course.id %}">{{ course.name }}</a></li>
        {% if folder %}
          <li><i class="fa fa-chevron-right"></i></li>
          <li><a href="{% url 'assignments:show_folder' course.id folder.id %}">{{ folder.name }}</a></li>
        {% endif %}
        {% if assignment %}
          <li><i class="fa fa-chevron-right"></i></li>
          <li><a href="{% url 'assignments:show' assignment.id %}">{% if assignment.is_quiz %}
            [QUIZ] {% endif %}{{ assignment.name }}</a></li>
          {% if student %}
            <li><i class="fa fa-chevron-right"></i></li>
            <li><a
              href="{% url 'assignments:student_submission' assignment.id student.id %}">{{ student.full_name }}</a>
            </li>
          {% endif %}
          {% if submission %}
            <li><i class="fa fa-chevron-right"></i></li>
            <li><a href="{% url 'submissions:show' submission.id %}">Submission #{{ submission_number }}</a></li>
          {% endif %}
        {% endif %}
      {% endif %}
      {% if venvs_app %}
        <li><i class="fa fa-chevron-right"></i></li>
        <li><a href="{% url 'venvs:index' %}">Virtual Environments</a></li>
      {% endif %}
      {% if nav_item %}
        <li><i class="fa fa-chevron-right"></i></li>
        <li><a href="">{{ nav_item }}</a></li>
      {% endif %}
      <li class="right"><i class="fa fa-sign-out"></i><a href="{% url 'auth:logout' %}">Logout
        ({{ request.user.username }})</a></li>
    {% endif %}
  </ul>
</div>

<div id="content">
  <div id="main">
    {% block main %}
    {% endblock %}
  </div>
  <div id="footer">
    <footer>
      {% block footer %}
        Turn-In is <a href="{{ REPO_URL }}" target="_blank">open source software</a>
        developed by Krishnan Shankar, John Beutner, and Theo Ouzhinski.
        Questions? Email <a href="mailto:{{ DEVELOPER_EMAIL }}">{{ DEVELOPER_EMAIL }}</a>
      {% endblock %}
    </footer>
  </div>
</div>

</body>

</html>

tin/templates/base_wo_head.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>{% block title %}Turn-In{% endblock %}</title>

  {% include "meta.html" %}

  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
  <link rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Open+Sans:100italic,400italic,700italic,100,400,700"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
          integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/themes/base/jquery-ui.min.css"
        integrity="sha512-8PjjnSP8Bw/WNPxF6wkklW6qlQJdWJc/3w/ZQPvZ/1bjVDkrrSqLe9mfPYrMxtnzsXFPc434+u4FHLnLjXTSsg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/jquery-ui.min.js"
          integrity="sha512-Ww1y9OuQ2kehgVWSD/3nhgfrb424O3802QYP/A5gPXoM4+rRjiKrjHdGxQKrMGQykmsJ/86oGdHszfcVgUr4hA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/css/selectize.default.min.css"
        integrity="sha512-pTaEn+6gF1IeWv3W1+7X7eM60TFu/agjgoHmYhAfLEU8Phuf6JKiiE8YmsNC0aCgQv4192s4Vai8YZ6VNM6vyQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/js/selectize.min.js"
          integrity="sha512-IOebNkvA/HZjMM7MxL0NYeLYEalloZ8ckak+NDtOViP7oiYzG5vn6WVXyrJDiJPhl4yRdmNAG49iuLmhkUdVsQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css"
        integrity="sha512-hasIneQUHlh06VNBe7f6ZcHmeRTLIaQWFd43YriJ0UND19bvYRauxthDg8E4eVNPm9bRUhr5JGeqH7FRFXQu5g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"
          integrity="sha512-D9gUyxqja7hBtkWpPWGt9wfbfaMGVt9gnyCvYa+jojwwPHLCzUm5i8rpk7vD7wNee9bA35eYIjobYPaQuKS1MQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js"
          integrity="sha512-axd5V66bnXpNVQzm1c7u1M614TVRXXtouyWCE+eMYl8ALK8ePJEs96Xtx7VVrPBc0UraCn63U1+ARFI3ofW+aA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
      hljs.highlightAll();
      hljs.initLineNumbersOnLoad();
  </script>
  <script>
      $(function () {
          $(".continuous-progress").css({height: "15px"}).progressbar({value: false})
      });
  </script>
  {% block head %}{% endblock %}
</head>

<body>
<div id="content">
  <div id="main">
    {% block main %}
    {% endblock %}
  </div>
</div>
</body>

</html>

tin/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block main %}

  <div class="login-box">
    <a href="{% url 'social:begin' 'ion' %}{% if request.GET.next %}?next={{ request.GET.next | urlencode }}{% endif %}"
       class="btn-ion">Log in with Ion</a>
    {% if debug %}
      <br/>
      <a href="
        {% url 'auth:password_login' %}{% if request.GET.next %}?next={{ request.GET.next | urlencode }}{% endif %}"
         class="btn-ion">Password login</a>
    {% endif %}
  </div>

{% endblock %}

tin/templates/meta.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Favicon Tags (https://realfavicongenerator.net/) -->

<!-- Browser -->
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}" media="(prefers-color-scheme: light)">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-dark-32x32.png' %}" media="(prefers-color-scheme: dark)">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}" media="(prefers-color-scheme: light)">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-dark-16x16.png' %}" media="(prefers-color-scheme: dark)">

<!-- Windows -->
<meta name="application-name" content="Turn-In">
<meta name="msapplication-TileColor" content="#4fab4f">
<meta name="msapplication-config" content="{% static 'favicon/browserconfig.xml' %}">

<!-- macOS -->
<link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#4fab4f">

<!-- iOS -->
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
<meta name="apple-mobile-web-app-title" content="Turn-In">
<meta name="apple-mobile-web-app-capable" content="yes">

<!-- Android -->
<link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
<meta name="theme-color" content="#4fab4f">

<!-- Legacy -->
<link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}" media="(prefers-color-scheme: light)">
<link rel="shortcut icon" href="{% static 'favicon/favicon-dark.ico' %}" media="(prefers-color-scheme: dark)">

{% comment "Old Favicon Tags" %}
<link rel="icon" href="{% static 'img/logos/logo-mark-black.svg' %}" type="image/svg+xml" sizes="any">
<link rel="icon" href="{% static 'img/logos/logo-mark-black-50.png' %}" type="image/png" sizes="50x50">
<link rel="icon" href="{% static 'img/logos/logo-mark-black-25.png' %}" type="image/png" sizes="25x25">
<link rel="icon" href="{% static 'img/logos/logo-mark-black-50.ico' %}" type="image/x-icon" sizes="50x50">
<link rel="icon" href="{% static 'img/logos/logo-mark-black-25.ico' %}" type="image/x-icon" sizes="25x25">
{% endcomment %}

tin/templates/password-login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Turn-In: Password login{% endblock %}

{% block main %}

  <h2>Password login</h2>

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
    {% else %}
      <p>Please login to see this page.</p>
    {% endif %}
  {% endif %}

  <form method="post" action="{% url 'auth:password_login' %}">
    {% csrf_token %}
    <div class="tbl">
      <div class="tbl-row">
        <span class="tbl-cell" style="padding-right:5px;">{{ form.username.label_tag }}</span>
        <span class="tbl-cell">{{ form.username }}</span>
      </div>
      <div class="tbl-row">
        <span class="tbl-cell" style="padding-right:5px;">{{ form.password.label_tag }}</span>
        <span class="tbl-cell">{{ form.password }}</span>
      </div>
    </div>

    <input type="submit" value="Login">
    <input type="hidden" name="next" value="{{ next }}">
  </form>

  {# Assumes you setup the password_reset view in your URLconf #}
{% endblock %}