tin/apps/auth/urls.py
from django.conf import settings
from django.contrib.auth import views as django_auth_views
from django.urls import path

from . import views

app_name = "auth"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]
if settings.DEBUG:
    urlpatterns.append(
        path(
            "password-login/",
            django_auth_views.LoginView.as_view(template_name="password-login.html"),
            name="password_login",
        )
    )

tin/apps/submissions/urls.py
from django.urls import path

from . import views

app_name = "submissions"

urlpatterns = [
    path("<int:submission_id>", views.show_view, name="show"),
    path("<int:submission_id>.json", views.show_json_view, name="show_json"),
    path("<int:submission_id>/download", views.download_view, name="download"),
    path("<int:submission_id>/kill", views.kill_view, name="kill"),
    path("<int:submission_id>/rerun", views.rerun_view, name="rerun"),
    path("<int:submission_id>/comment", views.comment_view, name="comment"),
    path(
        "<int:submission_id>/comment/edit/<int:comment_id>",
        views.edit_comment_view,
        name="edit_comment",
    ),
    path(
        "<int:submission_id>/comment/delete/<int:comment_id>",
        views.delete_comment_view,
        name="delete_comment",
    ),
    path("<int:submission_id>/publish", views.publish_view, name="publish"),
    path("<int:submission_id>/unpublish", views.unpublish_view, name="unpublish"),
    path("filter", views.filter_view, name="filter"),
    path("set-aborted-complete", views.set_aborted_complete_view, name="set_aborted_complete"),
    path(
        "set-past-timeout-complete",
        views.set_past_timeout_complete_view,
        name="set_past_timeout_complete",
    ),
]

tin/apps/users/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("theme/", views.change_theme, name="theme"),
]

tin/apps/venvs/urls.py
from django.urls import path

from . import views

app_name = "venvs"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("<int:venv_id>", views.show_view, name="show"),
    path("add", views.create_view, name="add"),
    path("<int:venv_id>/install_packages", views.install_packages_view, name="install_packages"),
]

tin/urls.py
from django.contrib import admin
from django.urls import include, path

from tin.apps.errors.views import handle_404_view, handle_500_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("courses/", include("tin.apps.courses.urls", namespace="courses")),
    path("assignments/", include("tin.apps.assignments.urls", namespace="assignments")),
    path("submissions/", include("tin.apps.submissions.urls", namespace="submissions")),
    path("venvs/", include("tin.apps.venvs.urls", namespace="venvs")),
    path("", include("tin.apps.auth.urls", namespace="auth")),
    path("", include("social_django.urls", namespace="social")),
]

handler404 = handle_404_view
handler500 = handle_500_view

tin/apps/assignments/models.py
import datetime
import logging
import os
import subprocess
from pathlib import Path
from typing import Literal

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models, transaction
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone

from ...sandboxing import get_action_sandbox_args, get_assignment_sandbox_args
from ..courses.models import Course, Period
from ..submissions.models import Submission
from ..venvs.models import Venv

logger = logging.getLogger(__name__)


class Folder(models.Model):
    """A folder for assignments.

    Each course can have multiple folders, and each
    assignment can be in a folder.
    """

    name = models.CharField(max_length=50)

    course = models.ForeignKey("courses.Course", on_delete=models.CASCADE, related_name="folders")

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("assignments:show_folder", args=[self.course.id, self.id])


class AssignmentQuerySet(models.query.QuerySet):
    def filter_permissions(self, user, *perms: Literal["-", "r", "w"]):
        """Filters based off of the permissions of the user and the course.

        An admin can always see everything. A teacher can only see courses they
        are the teachers for. Otherwise it filters it based off the course being archived
        and/or the permission of the course after archiving.

        Args:
            user: The user executing the query (``request.user``)
            *perms: Every permission listed is or-ed together.
                Each value can be - (hidden), r (read-only), or w (read-write)
        """
        if user.is_superuser:
            return self.all()
        else:
            perm_q = Q(course__archived=False)
            for perm in perms:
                perm_q |= Q(course__permission=perm)
            q = Q(course__teacher=user) | (Q(course__students=user, hidden=False) & perm_q)

            return self.filter(q).distinct()

    def filter_visible(self, user):
        r"""Filters assignments that are visible to a user

        Alias for calling :meth:`filter_permissions` with the permissions
        "r" and "w"
        """
        return self.filter_permissions(user, "r", "w")

    def filter_submittable(self, user):
        """Filters by assignments that can be submitted.

        .. warning::

            Do NOT use this if :attr:`~Assignment.is_quiz` is ``True``.
            In that case, the check should be done manually.
        """
        return self.filter_permissions(user, "w")

    def filter_editable(self, user):
        """Filters assignments if they're editable by the user"""
        if user.is_superuser:
            return self.all()
        else:
            return self.filter(course__teacher=user).distinct()


def upload_grader_file_path(assignment, _):  # pylint: disable=unused-argument
    """Get the location of the grader file for an assignment"""
    assert assignment.id is not None
    if assignment.grader_language == "J":
        return f"assignment-{assignment.id}/Grader.java"
    else:
        return f"assignment-{assignment.id}/grader.py"


class Assignment(models.Model):
    """An assignment (or quiz) for a student.

    If :attr:`~.Assignment.is_quiz` is ``True``, this
    model doubles as a quiz.

    The manager for this model is :class:`.AssignmentQuerySet`.
    """

    name = models.CharField(max_length=50)
    folder = models.ForeignKey(
        Folder,
        on_delete=models.SET_NULL,
        default=None,
        null=True,
        blank=True,
        related_name="assignments",
    )
    description = models.CharField(max_length=4096)
    markdown = models.BooleanField(default=False)

    language_details = models.ForeignKey(
        "Language",
        on_delete=models.CASCADE,
        related_name="assignment_set",
        null=False,
    )

    filename = models.CharField(max_length=50, default="main.py")

    course = models.ForeignKey(
        "courses.Course", on_delete=models.CASCADE, related_name="assignments"
    )

    venv = models.ForeignKey(
        Venv,
        on_delete=models.SET_NULL,
        default=None,
        null=True,
        blank=True,
        related_name="assignments",
    )

    points_possible = models.DecimalField(
        max_digits=6, decimal_places=3, validators=[MinValueValidator(1)]
    )

    assigned = models.DateTimeField(auto_now_add=True)
    due = models.DateTimeField()
    hidden = models.BooleanField(default=False)

    grader_file = models.FileField(upload_to=upload_grader_file_path, null=True)
    enable_grader_timeout = models.BooleanField(default=True)
    grader_timeout = models.IntegerField(default=300, validators=[MinValueValidator(10)])

    grader_has_network_access = models.BooleanField(default=False)

    has_network_access = models.BooleanField(default=False)

    # WARNING: this is the rate limit
    submission_limit_count = models.PositiveIntegerField(
        default=90,
        validators=[MinValueValidator(10)],
    )
    submission_limit_interval = models.PositiveIntegerField(
        default=30,
        validators=[MinValueValidator(10)],
    )
    submission_limit_cooldown = models.PositiveIntegerField(
        default=30,
        validators=[MinValueValidator(10)],
    )

    last_action_output = models.CharField(max_length=16 * 1024, default="", null=False, blank=True)

    is_quiz = models.BooleanField(default=False)
    QUIZ_ACTIONS = (("0", "Log only"), ("1", "Color Change"), ("2", "Lock"))
    quiz_action = models.CharField(max_length=1, choices=QUIZ_ACTIONS, default="2")
    quiz_autocomplete_enabled = models.BooleanField(default=False)
    quiz_description = models.CharField(max_length=4096, default="", null=False, blank=True)
    quiz_description_markdown = models.BooleanField(default=False)

    objects = AssignmentQuerySet.as_manager()

    submission_caps: models.QuerySet[SubmissionCap]

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("assignments:show", args=(self.id,))

    @property
    def grader_language(self) -> Literal["P", "J"]:
        """The language of the assignment (Python or Java)"""
        return self.language_details.language

    def within_submission_limit(self, student) -> bool:
        """Check if a student is within the submission limit for an assignment."""
        # teachers should have infinite submissions
        if not student.is_student or self.is_quiz or not self.submission_caps.exists():
            return True

        # note that this doesn't care about killed/incomplete submissions
        submission_count = self.submissions.filter(student=student).count()

        cap = self.find_submission_cap(student)
        return submission_count < cap

    def find_submission_cap(self, student) -> float:
        """Given a student, find the submission cap.

        This takes into account student overrides, and due dates.
        """
        if student.is_superuser or student.is_teacher:
            return float("inf")
        if timezone.localtime() > self.due:
            return self.submission_cap_after_due(student)
        return self.before_submission_cap(student)

    def find_student_override(self, student) -> SubmissionCap | None:
        """Find an :class:`.SubmissionCap` for a student.

        Returns ``None`` if no override exists.
        """
        return self.submission_caps.filter(student=student).first()

    def before_submission_cap(self, student) -> float:
        """Get the submission cap for an assignment before the due date.

        Returns ``float("inf")`` if no cap is found.
        """
        student_cap = self.find_student_override(student)
        if student_cap is not None and student_cap.submission_cap is not None:
            return student_cap.submission_cap
        cap = self.submission_caps.filter(student__isnull=True).first()
        if cap is not None and cap.submission_cap is not None:
            return cap.submission_cap
        return float("inf")

    def submission_cap_after_due(self, student) -> float:
        """Get the submission cap after the due date.

        Returns ``float("inf")`` if no cap is found.
        """
        student_cap = self.find_student_override(student)
        if student_cap is not None:
            # at least one of these must be set because of the model constraints
            return (
                student_cap.submission_cap_after_due
                if student_cap.submission_cap_after_due is not None
                else student_cap.submission_cap
            )
        cap = self.submission_caps.filter(student__isnull=True).first()
        if cap is not None and cap.submission_cap_after_due is not None:
            return cap.submission_cap_after_due
        # fall back to the submission cap before the due date
        return self.before_submission_cap(student)

    def make_assignment_dir(self) -> None:
        """Creates the directory where the assignment grader scripts go."""
        assignment_path = os.path.join(settings.MEDIA_ROOT, f"assignment-{self.id}")
        os.makedirs(assignment_path, exist_ok=True)

    def grader_exists(self) -> bool:
        """Check if a grader file exists."""
        if self.grader_file is None or self.grader_file.name is None:
            return False

        fpath = Path(settings.MEDIA_ROOT) / self.grader_file.name
        return fpath.exists()

    def save_grader_file(self, grader_text: str) -> None:
        """Save the grader file to the correct location.

        .. warning::

            Writing to files in directories not controlled by us without some

tin/apps/venvs/models.py
import logging
import os
import subprocess
from collections.abc import Iterable

from django.conf import settings
from django.db import models
from django.urls import reverse

from ... import sandboxing

logger = logging.getLogger(__name__)


class VenvCreationError(Exception):
    pass


class VenvExistsError(VenvCreationError):
    pass


class VenvQuerySet(models.query.QuerySet):
    def filter_visible(self, user):
        """Only superusers and teachers can see Venvs"""
        if user.is_superuser or user.is_teacher:
            return self.all()
        return self.none()

    def filter_editable(self, user):
        """Only admin can edit a venv"""
        if user.is_superuser:
            return self.all()
        return self.none()


class Venv(models.Model):
    """A Python Virtual Environment."""

    name = models.CharField(max_length=255, null=False, blank=False)

    fully_created = models.BooleanField(null=False)

    installing_packages = models.BooleanField(default=False, null=False)

    OUTPUT_MAX_LENGTH = 16 * 1024
    package_installation_output = models.CharField(
        max_length=OUTPUT_MAX_LENGTH, default="", null=False, blank=True
    )

    language = models.ForeignKey(
        "assignments.Language",
        on_delete=models.CASCADE,
        related_name="venv_set",
        null=False,
    )

    objects = VenvQuerySet.as_manager()

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<Virtualenv: {self.name}>"

    def get_absolute_url(self):
        return reverse("venvs:show", args=[self.id])

    @property
    def path(self):
        return os.path.join(settings.MEDIA_ROOT, "venvs", f"venv-{self.id}")

    def get_activation_env(self) -> dict[str, str]:
        """Returns information about the virtual environment.

        Returns:
            A dictionary with the keys

            * ``VIRTUAL_ENV``: the path to the virtual environment
            * ``PATH``: the modified ``$PATH`` variable
        """
        venv_path = self.path

        return {
            "VIRTUAL_ENV": venv_path,
            "PATH": os.path.join(venv_path, "bin") + os.pathsep + os.environ["PATH"],
        }

    def list_packages(self) -> list[list[str]] | None:
        """List all packages in a virtual environment.

        .. admonition:: TODO

            This parses the output from ``pip freeze``.
            Ideally, there should be a better way to do this.
        """
        env = dict(os.environ)
        env.update(self.get_activation_env())

        args = sandboxing.get_assignment_sandbox_args(
            ["pip", "freeze"],
            network_access=False,
            read_only=[self.path],
            extra_firejail_args=[f"--rlimit-fsize={settings.VENV_FILE_SIZE_LIMIT}"],
        )

        try:
            res = subprocess.run(
                args,
                check=False,
                env=env,
                capture_output=True,
                text=True,
            )
        except FileNotFoundError as e:
            logger.error("Cannot run processes: %s", e)
            raise FileNotFoundError from e

        if res.returncode != 0 or res.stderr:
            return None
        else:
            pkgs = []
            for line in res.stdout.splitlines():
                pkgs.append(line.split("==", 1))

            return pkgs

    def install_packages(self, pkgs: Iterable[str]) -> None:
        """Install packages"""
        self.installing_packages = True
        self.save()

        try:
            env = dict(os.environ)
            env.update(self.get_activation_env())

            args = sandboxing.get_assignment_sandbox_args(
                ["pip", "install", "--upgrade", "--", *pkgs],
                network_access=True,
                whitelist=[self.path],
                extra_firejail_args=[f"--rlimit-fsize={settings.VENV_FILE_SIZE_LIMIT}"],
            )

            try:
                res = subprocess.run(
                    args,
                    check=False,
                    env=env,
                    stdin=subprocess.DEVNULL,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                )
            except FileNotFoundError as e:
                logger.error("Cannot run processes: %s", e)
                raise FileNotFoundError from e

            try:
                self.package_installation_output = res.stdout.decode()[-self.OUTPUT_MAX_LENGTH :]
            except UnicodeDecodeError:
                self.package_installation_output = str(res.stdout)[-self.OUTPUT_MAX_LENGTH :]
        finally:
            self.installing_packages = False
            self.save()

tin/templates/assignments/show_folder.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Turn-In: {{ folder.name }}
{% endblock %}

{% block main %}

  <div class="header">
    <h2 class="left">{{ folder.name }}</h2>
    {% if is_teacher or request.user.is_superuser %}
      {% if request.user.is_superuser %}
        <a class="right tin-btn" href="{% url 'admin:assignments_folder_change' folder.id %}">Admin</a>
      {% endif %}
      <a class="right tin-btn" href="{% url 'assignments:edit_folder' course.id folder.id %}">Edit Folder</a>
    {% endif %}
  </div>

  <p>
    Teachers: {{ course.get_teacher_str }}<br>
    {% if period and is_student %}Your Period: {{ period | join:", " }}{% endif %}<br>
    {{ course.students.count }} student{{ course.students.count | pluralize }}
  </p>

  <ul id="assignment-list">
    {% if assignments %}
      {% for assignment in assignments %}
        <li>
          <div class="left">
            <a href="{% url 'assignments:show' assignment.id %}">{% if assignment.is_quiz %}
              [QUIZ] {% endif %}{{ assignment.name }}</a>{% if assignment.hidden %}<i> (Hidden)</i>{% endif %}
            {% if assignment in unsubmitted_assignments %}
              <br>
              <span class="italic">Not submitted</span>
            {% endif %}
          </div>
          <div class="right">
            Due: {{ assignment.due }}<br>
            Points possible: {{ assignment.points_possible }}
          </div>
        </li>
      {% endfor %}
    {% else %}
      <span class="italic">No assignments in this folder</span>
    {% endif %}
  </ul>

  {% if is_teacher or request.user.is_superuser %}
    <div>
      <a class="tin-btn" href="{% url 'assignments:add' course.id %}">New assignment</a>
    </div>
  {% endif %}

{% endblock %}

tin/templates/assignments/student_submission.html
{% extends "base.html" %}
{% load static %}

{% block title %}Turn-In: {{ course.name }}: {% if assignment.is_quiz %}[QUIZ] {% endif %}{{ assignment.name }}: {{ student.username }}{% endblock %}

{% block head %}
  <script src="{% static 'js/incomplete.js' %}"></script>
{% endblock %}

{% block main %}
<h2>{% if assignment.is_quiz %}[QUIZ] {% endif %}{{ assignment.name }}: {{ student.full_name }} ({{ student.username }})</h2>

<table id="assignment-info">
  <tr>
    <th>On time?</th>
    <td>
      {% if not latest_submission %}
        <span class="italic">Not yet submitted</span>
      {% elif latest_submission.is_on_time %}
        Yes
      {% else %}
        No
      {% endif %}
    </td>
  </tr>
  <tr>
    <th>Grade:</th>
    {% if latest_submission %}
      <td id="grade" class="{% if not latest_submission.complete %}incomplete{% endif %}" data-endpoint="{% url 'submissions:show_json' latest_submission.id %}" data-endpoint-key="formatted_grade">
        {% if not latest_submission.has_been_graded %}
          <span class="result-not-graded italic">Not graded</span>
        {% else %}
          {{ latest_submission.formatted_grade }}
        {% endif %}
      </td>
    {% else %}
      <td>
        <span class="italic">Not yet submitted</span>
      </td>
		{% endif %}
  </tr>
</table>

{% if submissions %}
  <h3 style="border-top:1px solid lightgray;padding-top:15px;">Grader output</h3>
  <div id="grader-output" class="code-result{% if not latest_submission.complete %} incomplete{% endif %}" data-endpoint="{% url 'submissions:show_json' latest_submission.id %}" data-endpoint-key="grader_output">
    <div class="result">
      <code><pre>{{ latest_submission.grader_output }}</pre></code>
    </div>
    {% if not latest_submission.complete %}
      <div class="continuous-progress"></div>
    {% endif %}
  </div>

  <h3 style="border-top:1px solid lightgray;padding-top:15px;">Grader errors</h3>
  <div id="grader-errors" class="code-result{% if not latest_submission.complete %} incomplete{% endif %}" data-endpoint="{% url 'submissions:show_json' latest_submission.id %}" data-endpoint-key="grader_errors">
    <div class="result">
      <code><pre>{{ latest_submission.grader_errors }}</pre></code>
    </div>
    {% if not latest_submission.complete %}
      <div class="continuous-progress"></div>
    {% endif %}
  </div>

  {% if not latest_submission.complete %}
    <div class="conditional-result incomplete italic" data-endpoint="{% url 'submissions:show_json' latest_submission.id %}" data-endpoint-key="kill_requested"{% if not latest_submission.kill_requested %} style="display: none"{% endif %} data-hide-when-complete="true">
      <br>
      This submission is in the process of being killed. This should complete within 15 seconds. If it does not, please email the tin administrators.
    </div>

    {% if not latest_submission.kill_requested %}
      <div class="conditional-result incomplete" data-endpoint="{% url 'submissions:show_json' latest_submission.id %}" data-endpoint-key="kill_requested" data-result-negate="true"{% if latest_submission.kill_requested %} style="display: none"{% endif %} data-hide-when-complete="true">
        <br>
        {% csrf_token %}
        <form method="post" action="{% url 'submissions:kill' latest_submission.id %}?next={{ request.get_full_path|urlencode }}">
          {% csrf_token %}
          <input type="submit" value="Kill submission">
        </form>
      </div>
    {% endif %}
  {% endif %}

  <h3 style="border-top:1px solid lightgray;padding-top:15px;">Latest submission</h3>
  <code><pre>{{ latest_submission_text }}</code></pre>
{% endif %}

<h3 style="border-top:1px solid lightgray;padding-top:15px;">Submissions</h3>
<table id="submission-list" class="has-border">
  <tr>
    <th style="min-width:125px;">Date submitted</th>
    <th style="min-width:65px;">On time?</th>
    <th style="min-width:80px;">Completed?</th>
    <th style="min-width:75px;">Grade</th>
  </tr>
  {% for submission in submissions %}
    <tr>
      {% if submission %}
      <td><a href="{% url 'submissions:show' submission.id %}">{{ submission.date_submitted }}</a></td>
      <td>{% if submission.is_on_time %}Yes{% else %}No{% endif %}</td>
      <td class="{% if submission == latest_submission and not submission.complete %}incomplete{% endif %}" data-endpoint="{% url 'submissions:show_json' submission.id %}" data-endpoint-key="complete">
        {% if submission.complete %}Yes{% else %}No{% endif %}
      </td>
      <td id="grade" class="{% if latest_submission == submission and not submission.complete %}incomplete{% endif %}" data-endpoint="{% url 'submissions:show_json' submission.id %}" data-endpoint-key="formatted_grade">
        {% if submission.has_been_graded %}
          {{ submission.formatted_grade }}
        {% else %}
          <span class="result-not-graded italic">Not graded</span>
        {% endif %}
      </td>
      {% endif %}
    </tr>
  {% endfor %}

  {% if not submissions %}
    <tr>
      <td colspan="4" class="italic center">No submissions</td>
    </tr>
  {% endif %}
</table>

{% if assignment.is_quiz %}
  <h3 style="border-top:1px solid lightgray;padding-top:15px;">Quiz Log Messages</h3>
  <a class="right tin-btn" href="{% url 'assignments:clear' assignment.id student.id %}">Reset Quiz</a>
  <br><br>
  <table id="submission-list" class="has-border">
    <tr>
      <th style="min-width:125px;">Date</th>
      <th style="min-width:200px;">Content</th>
      <th style="min-width:80px;">Severity</th>
    </tr>
    {% for message in log_messages %}
      <tr>
        <td>{{ message.date }}</td>
        <td>{{ message.content }}</td>
        <td>{{ message.severity }}</td>
      </tr>
    {% endfor %}

    {% if not log_messages %}
      <tr>
        <td colspan="4" class="italic center">No log messages</td>
      </tr>
    {% endif %}
  </table>
{% endif %}

{% endblock %}

tin/templates/assignments/student_submissions.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Turn-In: {% if assignment.is_quiz %}[QUIZ] {% endif %}{{ assignment.name }}: {{ student.username }}
{% endblock %}

{% block head %}
  <script src="{% static 'js/incomplete.js' %}"></script>
{% endblock %}

{% block main %}

  <div class="header">
    <h2 class="left">{% if assignment.is_quiz %}[QUIZ] {% endif %}{{ assignment.name }}: {{ student.full_name }}
      ({{ student.username }})</h2>
    {% if request.user.is_superuser %}
      <a class="right tin-btn" href="{% url 'admin:users_user_change' student.id %}">Admin (Student)</a>
    {% endif %}
  </div>

  <table id="assignment-info">
    <tr>
      <th>On time?</th>
      <td>
        {% if not latest_submission %}
          <span class="italic">Not yet submitted</span>
        {% elif latest_submission.is_on_time %}
          Yes
        {% else %}
          No
        {% endif %}
      </td>
    </tr>
    <tr>
      <th>Grade:</th>
      {% if latest_submission %}
        <td id="grade">
          {% include 'submissions/repr.html' with submission=latest_submission %}
        </td>
      {% else %}
        <td>
          <span class="italic">Not yet submitted</span>
        </td>
      {% endif %}
    </tr>
    {% if published_submission != latest_submission %}
        <tr>
          <th>Published grade:</th>
          <td id="last-grade">
            {% include 'submissions/repr.html' with submission=published_submission %}
          </td>
        </tr>
      {% endif %}
  </table>

  {% if assignment.is_quiz %}
    <h2 style="border-top:1px solid lightgray;padding-top:15px;">Quiz Log Messages</h2>
    <a class="right tin-btn" href="{% url 'assignments:clear' assignment.id student.id %}">Reset Quiz</a>
    <br><br>
    <table id="submission-list" class="has-border">
      <tr>
        <th style="min-width:125px;">Date</th>
        <th style="min-width:200px;">Content</th>
        <th style="min-width:80px;">Severity</th>
      </tr>
      {% for message in log_messages %}
        <tr>
          <td>{{ message.date }}</td>
          <td>{{ message.content }}</td>
          <td>{{ message.severity }}</td>
        </tr>
      {% endfor %}

      {% if not log_messages %}
        <tr>
          <td colspan="4" class="italic center">No log messages</td>
        </tr>
      {% endif %}
    </table>
  {% endif %}

  <h2 style="border-top:1px solid lightgray;padding-top:15px;">All Submissions</h2>
  <table id="submission-list" class="has-border">
    <tr>
      <th style="min-width:125px;">Date submitted</th>
      <th style="min-width:75px;">Grade</th>
      <th style="min-width:65px;">On time?</th>
      <th style="min-width:80px;">Completed?</th>
    </tr>
    {% for submission in submissions %}
      <tr>
        {% if submission %}
          <td><a href="{% url 'submissions:show' submission.id %}">{{ submission.date_submitted }}</a></td>
          <td id="grade">
            {% include 'submissions/repr.html' with submission=submission %}
          </td>
          <td>{% if submission.is_on_time %}Yes{% else %}No{% endif %}</td>
          <td class="{% if submission == latest_submission and not submission.complete %}incomplete{% endif %}"
              data-endpoint="{% url 'submissions:show_json' submission.id %}" data-endpoint-key="complete">
            {% if submission.complete %}Yes{% else %}No{% endif %}
          </td>
        {% endif %}
      </tr>
    {% endfor %}

    {% if not submissions %}
      <tr>
        <td colspan="4" class="italic center">No submissions</td>
      </tr>
    {% endif %}
  </table>


  <h2>Edit Submission Cap</h2>
  <p style="padding: 5px 0">
    To change the submission cap for this student, enter a new cap below.
    <br>
    {% with sub_count=submissions.count %}
      This student has used <strong>{{ sub_count }} {% if submission_cap is not None %} / {{ submission_cap }} {% endif %}</strong>
      submission{{ sub_count|pluralize }} on this assignment.
    {% endwith %}
  </p>
  <form method="POST">
    {% csrf_token %}
    {{ form.errors }}
    <div class="tbl">
      {% for field in form.visible_fields %}
        <div class="tbl-row">
          <span class="tbl-cell bold" style="padding-right:5px;min-width:200px;">{{ field.label }}</span>
          <span class="tbl-cell form-input">
            {{ field }}
            {% if field.help_text %}
              <br>{{ field.help_text }}
            {% endif %}
          </span>
        </div>
      {% endfor %}
      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}
    </div>
    <input class="tin-btn" type="submit" value="Save">
  </form>

{% endblock %}