tin/apps/assignments/urls.py
from django.urls import path

from . import views

app_name = "assignments"

urlpatterns = [
    path("<int:assignment_id>", views.show_view, name="show"),
    path("add/course/<int:course_id>", views.create_view, name="add"),
    path("<int:assignment_id>/edit", views.edit_view, name="edit"),
    path("<int:assignment_id>/delete", views.delete_view, name="delete"),
    path("<int:assignment_id>/grader", views.manage_grader_view, name="manage_grader"),
    path("<int:assignment_id>/grader/download", views.download_grader_view, name="download_grader"),
    path("<int:assignment_id>/files", views.manage_files_view, name="manage_files"),
    path(
        "<int:assignment_id>/files/download/<int:file_id>",
        views.download_file_view,
        name="download_file",
    ),
    path(
        "<int:assignment_id>/files/delete/<int:file_id>",
        views.delete_file_view,
        name="delete_file",
    ),
    path(
        "<int:assignment_id>/files/action/<int:action_id>",
        views.file_action_view,
        name="file_action",
    ),
    path(
        "<int:assignment_id>/students/<int:student_id>",
        views.student_submissions_view,
        name="student_submission",
    ),
    path("<int:assignment_id>/submit", views.submit_view, name="submit"),
    path("<int:assignment_id>/rerun", views.rerun_view, name="rerun"),
    path("<int:assignment_id>/quiz", views.quiz_view, name="quiz"),
    path("<int:assignment_id>/report", views.quiz_report_view, name="report"),
    path("<int:assignment_id>/end", views.quiz_end_view, name="quiz_end"),
    path("<int:assignment_id>/clear/<int:user_id>", views.quiz_clear_view, name="clear"),
    path("<int:assignment_id>/scores_csv", views.scores_csv_view, name="scores_csv"),
    path(
        "<int:assignment_id>/download_submissions",
        views.download_submissions_view,
        name="download_submissions",
    ),
    path("<int:assignment_id>/moss", views.moss_view, name="moss"),
    path("<int:assignment_id>/download_log", views.download_log_view, name="download_log"),
    path("folder/<int:course_id>/<int:folder_id>", views.show_folder_view, name="show_folder"),
    path("add/folder/<int:course_id>", views.create_folder_view, name="add_folder"),
    path("edit/folder/<int:course_id>/<int:folder_id>", views.edit_folder_view, name="edit_folder"),
    path(
        "delete/folder/<int:course_id>/<int:folder_id>",
        views.delete_folder_view,
        name="delete_folder",
    ),
    path("upload", views.upload_image, name="upload_image"),
]

tin/apps/auth/urls.py
from django.conf import settings
from django.contrib.auth import views as django_auth_views
from django.urls import path

from . import views

app_name = "auth"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]
if settings.DEBUG:
    urlpatterns.append(
        path(
            "password-login/",
            django_auth_views.LoginView.as_view(template_name="password-login.html"),
            name="password_login",
        )
    )

tin/apps/users/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("theme/", views.change_theme, name="theme"),
]

tin/apps/venvs/urls.py
from django.urls import path

from . import views

app_name = "venvs"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("<int:venv_id>", views.show_view, name="show"),
    path("add", views.create_view, name="add"),
    path("<int:venv_id>/install_packages", views.install_packages_view, name="install_packages"),
]

tin/urls.py
from django.contrib import admin
from django.urls import include, path

from tin.apps.errors.views import handle_404_view, handle_500_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("courses/", include("tin.apps.courses.urls", namespace="courses")),
    path("assignments/", include("tin.apps.assignments.urls", namespace="assignments")),
    path("submissions/", include("tin.apps.submissions.urls", namespace="submissions")),
    path("venvs/", include("tin.apps.venvs.urls", namespace="venvs")),
    path("", include("tin.apps.auth.urls", namespace="auth")),
    path("", include("social_django.urls", namespace="social")),
]

handler404 = handle_404_view
handler500 = handle_500_view

tin/apps/courses/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.urls import reverse


class CourseQuerySet(models.query.QuerySet):
    """Provide filtering utilities for courses."""

    def filter_visible(self, user):
        """Filters if a course is visible to a user.

        Admins can see all courses, teachers can only
        see course they teach, and students can only see non-archived
        courses OR courses that have permission "r" or "w"
        """
        if user.is_superuser:
            return self.all()
        else:
            return self.filter(
                Q(teacher=user)
                | (Q(students=user) & (Q(archived=False) | Q(permission="r") | Q(permission="w")))
            ).distinct()

    def filter_editable(self, user):
        """Filter courses a user can edit."""
        if user.is_superuser:
            return self.all()
        else:
            return self.filter(teacher=user).distinct()


class Course(models.Model):
    """A TJHSST Course

    e.g. Foundations of Computer Science
    """

    SORT_BY = (("due_date", "Due Date"), ("name", "Name"))
    PERMISSIONS = (
        ("w", "view and submit assignments"),
        ("r", "view assignments"),
        ("-", "see nothing"),
    )

    name = models.CharField(max_length=50, blank=False)
    teacher = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=False,
        related_name="taught_courses",
    )
    students = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="courses", blank=True)

    created = models.DateTimeField(auto_now_add=True)

    sort_assignments_by = models.CharField(max_length=30, choices=SORT_BY, default="due_date")

    archived = models.BooleanField(default=False)
    permission = models.CharField(max_length=1, choices=PERMISSIONS, default="r")

    objects = CourseQuerySet.as_manager()

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("courses:show", args=[self.id])

    def get_teacher_str(self) -> str:
        """Get a string of the last names of all teachers in a course"""
        return ", ".join(t.last_name for t in self.teacher.all())

    def is_student_in_course(self, user) -> bool:
        """Check if a student is registered in the course"""
        return self.students.contains(user)

    def is_only_student_in_course(self, user) -> bool:
        """Check if a user is the only student in a course"""
        return self.is_student_in_course(user) and not (
            user.is_superuser or user in self.teacher.all()
        )


class Period(models.Model):
    """A Period, or a Block

    e.g. Period 7
    """

    name = models.CharField(max_length=50, blank=False)
    course = models.ForeignKey(
        Course, null=True, on_delete=models.CASCADE, related_name="period_set"
    )

    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="taught_periods",
    )

    students = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="periods", blank=True)

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("courses:students", args=[self.course.id]) + f"?period={self.id}"


class StudentImportUser(models.Model):
    """A student that is to be added to a course when they log in"""

    user = models.CharField(max_length=15, unique=True)

    class Meta:
        verbose_name = "Imported Student"

    def __str__(self):
        return self.user

    def __repr__(self):
        return self.user


class StudentImport(models.Model):
    students = models.ManyToManyField(StudentImportUser, related_name="users")
    course = models.OneToOneField(Course, unique=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Student Import"

    def __str__(self):
        return f"Import into {self.course.name}"

    def __repr__(self):
        return f"Import into {self.course.name}"

    def get_absolute_url(self):
        return reverse("courses:import_students", args=[self.course.id])

    def queue_users(self, usernames):
        """Add usernames to a queue of students to add to a course"""
        for username in usernames:
            import_user_object = StudentImportUser.objects.get_or_create(user=username)[0]
            self.students.add(import_user_object)
        self.save()

tin/apps/submissions/forms.py
from django import forms
from django.db.models import Q

from ..assignments.models import Assignment, Folder
from ..courses.models import Course, Period
from ..users.forms import UserMultipleChoiceField
from ..users.models import User
from .models import Comment, Submission


class CustomModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        if isinstance(obj, Course):
            return obj.name
        elif isinstance(obj, Folder):
            return f"{obj.name} (in {obj.course.name})"
        elif isinstance(obj, Assignment):
            if obj.folder:
                return f"{obj.name} (in {obj.folder.name} in {obj.course.name})"
            return f"{obj.name} (in {obj.course.name})"
        elif isinstance(obj, Period):
            return f"{obj.name} (in {obj.course.name})"
        return super().label_from_instance(obj)


class FilterForm(forms.Form):
    ORDER_CHOICES = (
        ("", "None"),
        ("date_submitted", "Oldest first"),
        ("-date_submitted", "Newest first"),
        ("assignment__name", "Assignment name, A to Z"),
        ("-assignment__name", "Assignment name, Z to A"),
        ("assignment__course__name", "Course name, A to Z"),
        ("-assignment__course__name", "Course name, Z to A"),
        ("assignment__folder__name", "Folder name, A to Z"),
        ("-assignment__folder__name", "Folder name, Z to A"),
        ("student__username", "Student username, A to Z"),
        ("-student__username", "Student username, Z to A"),
        ("student__last_name", "Student last name, A to Z"),
        ("-student__last_name", "Student last name, Z to A"),
        ("student__first_name", "Student first name, A to Z"),
        ("-student__first_name", "Student first name, Z to A"),
        ("points_received", "Points received, low to high"),
        ("-points_received", "Points received, high to low"),
        ("assignment__points_possible", "Points possible, low to high"),
        ("-assignment__points_possible", "Points possible, high to low"),
    )

    courses = CustomModelMultipleChoiceField(
        label="Courses", queryset=Course.objects.all().order_by("name"), required=False
    )
    folders = CustomModelMultipleChoiceField(
        label="Folders", queryset=Folder.objects.all().order_by("name"), required=False
    )
    assignments = CustomModelMultipleChoiceField(
        label="Assignments", queryset=Assignment.objects.all().order_by("name"), required=False
    )
    periods = CustomModelMultipleChoiceField(
        label="Periods", queryset=Period.objects.all().order_by("name"), required=False
    )
    students = UserMultipleChoiceField(
        label="Students",
        queryset=User.objects.filter(is_student=True).order_by("last_name", "first_name"),
        required=False,
    )
    start_date = forms.DateTimeField(label="From", required=False)
    end_date = forms.DateTimeField(label="To", required=False)
    is_latest_publish = forms.BooleanField(label="Is latest or published?", required=False)
    is_latest = forms.BooleanField(label="Is latest?", required=False)
    is_published = forms.BooleanField(label="Is published?", required=False)
    has_been_graded = forms.BooleanField(label="Is graded?", required=False)
    has_not_been_graded = forms.BooleanField(label="Is not graded?", required=False)
    is_complete = forms.BooleanField(label="Is complete?", required=False)
    is_incomplete = forms.BooleanField(label="Is incomplete?", required=False)
    min_points = forms.IntegerField(label="Min points", required=False)
    max_points = forms.IntegerField(label="Max points", required=False)
    points_possible = forms.IntegerField(label="Total points possible", required=False)

    limit = forms.IntegerField(label="Limit", initial=1000, required=False)
    order_by_1 = forms.ChoiceField(
        label="Order by", choices=ORDER_CHOICES, required=False, initial=""
    )
    order_by_2 = forms.ChoiceField(
        label="Then by", choices=ORDER_CHOICES, required=False, initial=""
    )
    order_by_3 = forms.ChoiceField(
        label="Then by", choices=ORDER_CHOICES, required=False, initial=""
    )
    order_by_4 = forms.ChoiceField(
        label="Then by", choices=ORDER_CHOICES, required=False, initial=""
    )
    order_by_5 = forms.ChoiceField(
        label="Then by", choices=ORDER_CHOICES, required=False, initial=""
    )

    def get_results(self):
        """Returns a queryset of submissions matching the form's filters"""
        queryset = Submission.objects.all()

        if self.cleaned_data["courses"]:
            queryset = queryset.filter(assignment__course__in=self.cleaned_data["courses"])

        if self.cleaned_data["folders"]:
            queryset = queryset.filter(assignment__folder__in=self.cleaned_data["folders"])

        if self.cleaned_data["assignments"]:
            queryset = queryset.filter(assignment__in=self.cleaned_data["assignments"])

        if self.cleaned_data["periods"]:
            query = queryset.none()
            for period in self.cleaned_data["periods"]:
                query |= Q(student__in=period.students.all()) & Q(assignment__course=period.course)
            queryset = queryset.filter(query)

        if self.cleaned_data["students"]:
            queryset = queryset.filter(student__in=self.cleaned_data["students"])

        if self.cleaned_data["start_date"]:
            queryset = queryset.filter(date_submitted__gte=self.cleaned_data["start_date"])

        if self.cleaned_data["end_date"]:
            queryset = queryset.filter(date_submitted__lte=self.cleaned_data["end_date"])

        if self.cleaned_data["has_been_graded"]:
            queryset = queryset.filter(has_been_graded=True)

        if self.cleaned_data["has_not_been_graded"]:
            queryset = queryset.filter(has_been_graded=False)

        if self.cleaned_data["is_complete"]:
            queryset = queryset.filter(complete=True)

        if self.cleaned_data["is_incomplete"]:
            queryset = queryset.filter(complete=False)

        if self.cleaned_data["min_points"]:
            queryset = queryset.filter(points_received__gte=self.cleaned_data["min_points"])

        if self.cleaned_data["max_points"]:
            queryset = queryset.filter(points_received__lte=self.cleaned_data["max_points"])

        if self.cleaned_data["points_possible"]:
            queryset = queryset.filter(
                assignment__points_possible=self.cleaned_data["points_possible"]
            )

        order_bys = [self.cleaned_data[f"order_by_{i}"] for i in range(1, 6)]
        order_bys = filter(None, order_bys)  # Remove empty selections
        if order_bys:
            queryset = queryset.order_by(*order_bys)

        # This is done last to minimize queryset evaluation
        # However, slicing must be done last (see limit below)
        if self.cleaned_data["is_latest_publish"]:
            latest_publish_ids = [s.pk for s in queryset if (s.is_latest_publish or s.is_latest)]
            queryset = queryset.filter(pk__in=latest_publish_ids)

        if self.cleaned_data["is_latest"]:
            latest_ids = [s.pk for s in queryset if s.is_latest]
            queryset = queryset.filter(pk__in=latest_ids)

        if self.cleaned_data["is_published"]:
            published_ids = [s.pk for s in queryset if s.is_latest_publish]
            queryset = queryset.filter(pk__in=published_ids)

        if self.cleaned_data["limit"]:
            queryset = queryset[: self.cleaned_data["limit"]]

        return queryset


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text", "point_override"]
        widgets = {
            "text": forms.Textarea(attrs={"cols": 120, "rows": 5}),
            "point_override": forms.NumberInput(attrs={"step": 0.5}),
        }

tin/apps/users/forms.py
from django import forms


class UserMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, user):  # pylint: disable=arguments-differ
        return f"{user.full_name} ({user.username})"

tin/apps/users/views.py
from __future__ import annotations

from django import http
from django.contrib.auth.decorators import login_required

from tin.apps.users.forms import ThemeForm


@login_required
def change_theme(request):
    """Sets the color theme"""
    if request.method == "POST":
        form = ThemeForm(request.POST)
        if form.is_valid():
            request.user.dark_mode = form.cleaned_data["dark_mode"]
            request.user.save()
            return http.JsonResponse({"success": True})
        else:
            return http.JsonResponse(
                {"success": False, "errors": form.errors.as_json()}, status=400
            )
    raise http.Http404

tin/templates/submissions/edit_comment.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Turn-In: {{ submission.student.full_name }} ({{ submission.student.username }}): Submission #{{ submission_number }}: Edit comment
{% endblock %}

{% block main %}

  <h2>{{ submission.student.full_name }} ({{ submission.student.username }}): Submission #{{ submission_number }}: Edit comment</h2>

  {% if form.errors %}
    <h3 class="errors">Please correct the errors below.</h3>
    <ul class="errors">
      {% for field in form %}
        {% for error in field.errors %}
          <li>{{ field.label }}: {{ error }}</li>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <div class="tbl">
      {% for field in form %}
        <div class="tbl-row">
          <span class="tbl-cell bold" style="vertical-align:top;padding-right:5px;">{{ field.label_tag }}</span>
          <span class="tbl-cell form-input"{% if field.help_text %} style="padding-bottom:5px"{% endif %}>{{ field }}
            {% if field.help_text %}<br>{{ field.help_text }}{% endif %}</span>
        </div>
      {% endfor %}
    </div>
    <input type="submit" value="Save">
    &emsp;<a style="color:red" href="{% url 'submissions:delete_comment' submission.id comment.id %}">Delete Comment</a>
  </form>

{% endblock %}

tin/templates/submissions/filter.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Turn-In: Filter submissions
{% endblock %}

{% block head %}
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
        integrity="sha512-f0tzWhCwVFS3WeYaofoLWkTP62ObhewQ1EZn65oSYDZUg1+CyywGKkWzm8BxaJj5HGKI72PnMH9jYyIFz+GH7g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
          integrity="sha512-AIOTidJAcHBH2G/oZv9viEGXRqDNmfdPVPYOYKGy3fti0xIplnlgMHUGfuNRzC6FkzIo0iIxgFnr9RikFxK+sw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script type="text/javascript">
      $(document).ready(function () {
          $("#id_courses").selectize();
          $("#id_folders").selectize();
          $("#id_assignments").selectize();
          $("#id_periods").selectize();
          $("#id_students").selectize();
          $("<div></div>").css({"border-top": "1px solid lightgray", "margin-top": "10px", "margin-bottom": "15px"}).insertBefore($("#id_limit").parent().parent());
      });
  </script>
  <script type="text/javascript">
      $(document).ready(function () {
          $("#id_start_date,#id_end_date").datetimepicker({
              lazyInit: true,
              timepicker: true,
              format: "Y-m-d H:i:s",
          });
      });
  </script>
{% endblock %}

{% block main %}

  <div class="header">
    <h2 class="left">Filter submissions</h2>
    {% if request.user.is_superuser %}
      <a class="right tin-btn" href="{% url 'admin:submissions_submission_changelist' %}">Admin</a>
    {% endif %}
  </div>

  {% if form.errors %}
    <h3 class="errors">Please correct the errors below.</h3>
    <ul class="errors">
      {% for field in form %}
        {% for error in field.errors %}
          <li>{{ field.label }}: {{ error }}</li>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <div class="tbl">
      {% for field in form %}
        <div class="tbl-row">
          <span class="tbl-cell bold" style="vertical-align:top;padding-right:5px;">{{ field.label_tag }}</span>
          <span class="tbl-cell form-input"{% if field.help_text %} style="padding-bottom:5px"{% endif %}>{{ field }}
            {% if field.help_text %}<br>{{ field.help_text }}{% endif %}</span>
        </div>
      {% endfor %}
    </div>
    <input type="submit" name="list_submissions" value="Apply filter">

    {% if action == "filter" %}
      <p>
        Tips:
      </p>
      <ul>
        <li>
          Multiple selections for a field (e.g. two selected assignments) are ORed together, while different fields (a selected course and student) are ANDed.
        </li>
        <li>
          Blank fields are ignored.
        </li>
        <li>
          It is easy to create impossible filters, like selecting an assignment and multiple folders (an assignment can only be in one folder). Be careful!
        </li>
        <li>
          Vague filters that match many submissions will take considerably longer to load.
        </li>
        <li>
          The "Limit" filter can be unset to show all matching submissions, but doing so is highly discouraged.
        </li>
      </ul>
    {% elif action == "show" %}
      <h2 style="border-top:1px solid lightgray;padding-top:15px;">Results</h2>
      <p>Showing {{ submissions|length }} submission{{ submissions|pluralize }}. <input type="submit" name="view_code" value="View code for each submission"></p>
      <table id="submission-list" class="has-border">
        <tr>
          <th style="min-width:125px;">Date submitted</th>
          <th style="min-width:75px;">Course</th>
          <th style="min-width:65px;">Folder</th>
          <th style="min-width:80px;">Assignment</th>
          <th style="min-width:75px;">Student</th>
          <th style="min-width:75px;">Grade</th>
          <th style="min-width:75px;">On time?</th>
          <th style="min-width:75px;">Completed?</th>
        </tr>
        {% for submission in submissions %}
          <tr>
            {% if submission %}
              <td><a href="{% url 'submissions:show' submission.id %}">{{ submission.date_submitted }}</a></td>
              <td><a href="{% url 'courses:show' submission.assignment.course.id %}">{{ submission.assignment.course }}</a></td>
              <td>
                {% if submission.assignment.folder %}
                  <a href="{% url 'assignments:show_folder' submission.assignment.course.id submission.assignment.folder.id %}">{{ submission.assignment.folder }}</a>
                {% else %}
                  <i>-</i>
                {% endif %}
              </td>
              <td><a href="{% url 'assignments:show' submission.assignment.id %}">{{ submission.assignment }}</a></td>
              <td><a href="{% url 'assignments:student_submission' submission.assignment.id submission.student.id %}">{{ submission.student.full_name }} ({{ submission.student.username }})</a></td>
              <td>{% include 'submissions/repr.html' with submission=submission %}</td>
              <td>{% if submission.is_on_time %}Yes{% else %}No{% endif %}</td>
              <td>{% if submission.complete %}Yes{% else %}No{% endif %}</td>
            {% endif %}
          </tr>
        {% endfor %}

        {% if not submissions %}
          <tr>
            <td colspan="8" class="italic center">Nothing matched your filter!</td>
          </tr>
        {% endif %}
      </table>
    {% elif action == "show_code" %}
      <h2 class="new-page" style="border-top:1px solid lightgray;padding-top:15px;">Results</h2>
      <p>Showing the code for {{ submissions|length }} submission{{ submissions|pluralize }}. <input type="submit" name="list_submissions" value="Back to list"> <input type="button" value="Print" onClick="window.print()"></p>

      {% for submission, submission_text in submissions %}
        {% if submission %}
          <h3>
            [{{ submission.date_submitted }}]
            {{ submission.assignment.course }}
            {% if submission.assignment.folder %}>> {{ submission.assignment.folder }}{% endif %}
            >> {{ submission.assignment }}
            >> {{ submission.student }}
            {% if submission.points %}
              >> {{ submission.points | floatformat:"-3" }} / {{ submission.points_possible | floatformat:"-3" }}
              ({{ submission.grade_percent_num | floatformat:"-2" }}%)
            {% else %}
              >> Not graded
            {% endif %}
            {% if not submission.is_on_time %}*late*{% endif %}
            {% if not submission.complete %}*incomplete*{% endif %}
          </h3>
          <pre><code>{{ submission_text }}</code></pre>
        {% endif %}
      {% endfor %}
    {% endif %}

  </form>

{% endblock %}

tin/templates/submissions/repr.html
{% if not submission.complete %}
  <span class="result-not-graded italic incomplete" data-endpoint="{% url 'submissions:show_json' submission.id %}" data-endpoint-key="formatted_grade">Not graded</span>
{% elif not submission.has_been_graded %}
  <span class="result-not-graded italic">Not graded</span>
{% else %}
  <b>{{ submission.points | floatformat:"-3" }}</b> / {{ submission.points_possible | floatformat:"-3" }} ({{ submission.grade_percent_num | floatformat:"-2" }}%)
  {% if submission.is_published %}
    {% if submission.is_latest_publish %}
      <i class="fa fa-star" style="color: red" data-toggle="tooltip" title="Published {{ submission.published_submission.date }}"></i>
    {% else %}
      <i class="fa fa-star-o" style="color: red" data-toggle="tooltip" title="Published {{ submission.published_submission.date }}"></i>
    {% endif %}
  {% endif %}
  {% if submission.last_run %}
    <i class="fa fa-repeat" style="color: {{ submission.rerun_color }}" data-toggle="tooltip" title="Rerun {{ submission.last_run }}"></i>
  {% endif %}
  {% if submission.comments.count > 0 %}
      {% if submission.comments.count == 1 %}
        <i class="fa fa-comment" data-toggle="tooltip" title="Has a teacher comment"></i>
      {% else %}
        <i class="fa fa-comments" data-toggle="tooltip" title="Has teacher comments"></i>
      {% endif %}
      {% if submission.point_override != 0 %}
        <span style="color: {% if submission.point_override > 0 %}green{% else %}red{% endif %};" data-toggle="tooltip" title="Points were altered by a teacher">
          <b>
            {% if submission.point_override > 0 %}
              [+{{ submission.point_override | floatformat:"-3" }}]
            {% else %}
              [{{ submission.point_override | floatformat:"-3" }}]
            {% endif %}
          </b>
        </span>
      {% endif %}
  {% endif %}
{% endif %}